steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'terraform init'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      
        cd $BRANCH_NAME
        terraform init
