steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:0.12.3'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      export TF_INPUT=0
      
        terraform init -upgrade 
  id: 'tf apply'
  name: 'hashicorp/terraform:0.12.3'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
        terraform apply -auto-approve
