steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
  - id: 'tf init'
  name: 'terraform init'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      
      ls -lrta
      terraform-0.11.14 init 
      
 


      
       
       
