steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
  - id: 'tf init'
  name: 'hashicorp/terraform:0.11.14'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd .docker
      ls -lrta
      terraform init 
      
 


      
       
       
