steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
  - id: 'tf install'
  name: 'terraform install'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      
      ls -lrta
      terraform -install-autocomplete
      
 


      
       
       
