steps:
- id: 'branch name'
  name: 'alpine'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      - id: 'tf init'
       name: 'hashicorp/terraform:0.11.14'
       args:  terraform init


