steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:0.12.3'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init 
      terraform plan
      terraform apply -auto-approve
   

      
 
